### ISSUE TITLE
initct1: Unknown instance

### ISSUE THREAD

**Issue by brenden77** [JeffersonDing/SynologyMerge#1]
Hello,

I tried your script on my Synology DS412+ and received this error when trying to migrate my apps. I'm not sure if you would know why this happened. But figured i'd report it. I think I will try stepping through the commands to see if I can figure out what part failed.
![image](https://user-images.githubusercontent.com/61955261/110866637-6fa7bf80-8293-11eb-8db0-ae733c4e6e3a.png)

**Comment by jeofo** [comment]
Yeah, I think what's happening here is that `Apache`  isn't running at the moment and the first line of the scripts tries to stop the service which doesn't have an instance. What you can do here is either kind of start the `web server` on the NAS so that Apache is running or modify the script so that that line is removed if it's already stopped.

**Comment by brenden77** [comment]
> Yeah, I think what's happening here is that `Apache` isn't running at the moment and the first line of the scripts tries to stop the service which doesn't have an instance. What you can do here is either kind of start the `web server` on the NAS so that Apache is running or modify the script so that that line is removed if it's already stopped.

Yes, I think you're correct. I had gone through and stopped every package that I could beforehand. Ha! 

I'd just come back to report it was the service stop that gave out. Thanks for your reply just the same!
![image](https://user-images.githubusercontent.com/61955261/110868233-3886dd80-8296-11eb-88e1-71e11badb2c2.png)
